[package]
name = "xash3d-sdk-tools"
version = "0.1.0"
publish = false
license = "Unlicense"
authors = ["Denis Drakhnia <numas13@gmail.com>"]
edition = "2021"
rust-version = "1.77"

[[bin]]
name = "gen-resources"
path = "gen-resources.rs"
